name: FSSRP
channels:
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - python=3.9
  - pandas
  - seaborn
  - tqdm
  - pyarrow
  - fastparquet
  - tabulate
  - pip:
    - parquet
    - river
    - mrmr_selection